include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = badgeindicatorprefs
badgeindicatorprefs_FILES = DIPRootListController.m DIPHeaderView.m
badgeindicatorprefs_INSTALL_PATH = /Library/PreferenceBundles
badgeindicatorprefs_FRAMEWORKS = UIKit
badgeindicatorprefs_PRIVATE_FRAMEWORKS = Preferences
badgeindicatorprefs_CFLAGS = -fobjc-arc -Wno-deprecated-declarations

include $(THEOS_MAKE_PATH)/bundle.mk
